# Generated by Django 6.0.7 on 2026-07-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('slug', models.SlugField(unique=True, verbose_name='رابط فرعي')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل الزوار',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهارة')),
                ('proficiency', models.IntegerField(default=80, verbose_name='نسبة الإتقان')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف مختصر للمشروع')),
                ('detailed_description', models.TextField(verbose_name='الوصف التفصيلي والميزات')),
                ('technologies', models.CharField(max_length=200, verbose_name='التقنيات المستخدمة (تفصل بفاصلة)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة المشروع الرئيسية')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='رابط GitHub')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='رابط المعاينة الحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='showcase.category', verbose_name='قسم المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
